IDIR =../include
CC=g++
CFLAGS=-ggdb -I$(IDIR) -Wall

ODIR=obj
LDIR =../lib

LIBS=-lm

_DEPS = #server.hpp
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = server.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))


$(ODIR)/%.o: %.cpp $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

server: $(OBJ)
	g++ -o $@ $^ $(CFLAGS) $(LIBS) -pthread

.PHONY: clean

clean:
	rm -f server $(ODIR)/*.o *~ core $(INCDIR)/*~ 
